apiVersion: v1
kind: Service
metadata:
  name: ingress-metallb
  namespace: ingress
spec:
  selector:
    name: traefik-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443